const foodItem= [
{
    id : 1,
    name : 'Donuts',
    category : 'biryani',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
{
    id : 2,
    name : 'Donuts',
    category : 'biryani',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
{
    id : 3,
    name : 'Donuts',
    category : 'biryani',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
{
    id : 4,
    name : 'Donuts',
    category : 'chicken',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
{
    id : 5,
    name : 'Donuts',
    category : 'chicken',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
{
    id : 6,
    name : 'Donuts',
    category : 'paneer',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
{
    id : 7,
    name : 'Donuts',
    category : 'paneer',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
{
    id : 8,
    name : 'Donuts',
    category : 'paneer',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
{
    id : 9,
    name : 'Donuts',
    category : 'paneer',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
{
    id : 10,
    name : 'Donuts',
    category : 'south indian',
    rating : 4.3,
    price : 15,
    img : 'images/gumball.png',
    quantity : 1,
},
]

export {foodItem};