const foodItem= [
    {
        id : 1,
        name : 'Single donut',
        category : 'Donuts',
        rating : 4,
        price : 15,
        img : 'images/donuts/1.png',
        quantity : 1,
    },
    {
        id : 2,
        name : 'Pack of 2 Donuts',
        category : 'Donuts',
        rating : 4.3,
        price : 25,
        img : 'images/donuts/2.jpg',
        quantity : 1,
    },
    {
        id : 3,
        name : 'Pack of 12 Donuts',
        category : 'Donuts',
        rating : 4.9,
        price : 100,
        img : 'images/donuts/3.jpg',
        quantity : 1,
    },
    {
        id : 4,
        name : 'Pack of 3 Donuts',
        category : 'Donuts',
        rating : 3.9,
        price : 50,
        img : 'images/donuts/4.jpg',
        quantity : 1,
    },
    {
        id : 5,
        name : 'Pack of 9 Donuts',
        category : 'Donuts',
        rating : 4.6,
        price : 60,
        img : 'images/donuts/5.jpg',
        quantity : 1,
    },
    {
        id : 6,
        name : 'Strawberry cone',
        category : 'Icecream',
        rating : 4.5,
        price : 12,
        img : 'images/icecream/6.jpg',
        quantity : 1,
    },
    {
        id : 7,
        name : 'Blueberry sundae',
        category : 'Icecream',
        rating : 4.7,
        price : 15,
        img : 'images/icecream/7.jpg',
        quantity : 1,
    },
    {
        id : 8,
        name : 'Pack of 7 sticks',
        category : 'Icecream',
        rating : 3.7,
        price : 50,
        img : 'images/icecream/8.jpg',
        quantity : 1,
    },
    {
        id : 9,
        name : 'Choco Chip Stick',
        category : 'Icecream',
        rating : 4.5,
        price : 18,
        img : 'images/icecream/9.jpg',
        quantity : 1,
    },
    {
        id : 10,
        name : 'Strawberry sundae',
        category : 'Icecream',
        rating : 4.8,
        price : 25,
        img : 'images/icecream/10.jpg',
        quantity : 1,
    },
    {
        id : 11,
        name : 'Bubblegum shake',
        category : 'Shakes',
        rating : 4.3,
        price : 25,
        img : 'images/shakes/11.jpg',
        quantity : 1,
    },
    {
        id : 12,
        name : 'Mint Mohito',
        category : 'Shakes',
        rating : 4.5,
        price : 24,
        img : 'images/shakes/12.jpg',
        quantity : 1,
    },
    {
        id : 13,
        name : 'Oreo Shake',
        category : 'Shakes',
        rating : 4.8,
        price : 27,
        img : 'images/shakes/13.jpg',
        quantity : 1,
    },
    {
        id : 14,
        name : 'Strawberry Shake',
        category : 'Shakes',
        rating : 4.6,
        price : 25,
        img : 'images/shakes/14.jpg',
        quantity : 1,
    },
    {
        id : 15,
        name : 'Choco Shake',
        category : 'Shakes',
        rating : 4.5,
        price : 30,
        img : 'images/shakes/15.jpg',
        quantity : 1,
    },
    {
        id : 16,
        name : 'Dark Chocolate',
        category : 'Sweets',
        rating : 4.5,
        price : 9,
        img : 'images/sweets/16.jpg',
        quantity : 1,
    },
    {
        id : 17,
        name : 'Gems',
        category : 'Sweets',
        rating : 4.7,
        price : 5,
        img : 'images/sweets/17.jpg',
        quantity : 1,
    },
    {
        id : 18,
        name : 'Chocolates - 10',
        category : 'Sweets',
        rating : 4.9,
        price : 50,
        img : 'images/sweets/18.jpg',
        quantity : 1,
    },
    {
        id : 19,
        name : 'Sour Bites',
        category : 'Sweets',
        rating : 4.2,
        price : 10,
        img : 'images/sweets/19.jpg',
        quantity : 1,
    },
    {
        id : 20,
        name : 'CheeseCake',
        category : 'Sweets',
        rating : 4.5,
        price : 20,
        img : 'images/sweets/20.jpg',
        quantity : 1,
    },
    {
        id : 21,
        name : 'Rainbow cake',
        category : 'Cake',
        rating : 4.8,
        price : 99,
        img : 'images/cake/21.jpg',
        quantity : 1,
    },
    {
        id : 22,
        name : 'Chocolate cake',
        category : 'Cake',
        rating : 4.6,
        price : 119,
        img : 'images/cake/22.jpg',
        quantity : 1,
    },
    {
        id : 23,
        name : 'Plum cake',
        category : 'Cake',
        rating : 4.5,
        price : 109,
        img : 'images/cake/23.jpg',
        quantity : 1,
    },
    {
        id : 24,
        name : 'Strawberry cake',
        category : 'Cake',
        rating : 4.8,
        price : 119,
        img : 'images/cake/24.jpg',
        quantity : 1,
    },
    {
        id : 25,
        name : 'Butterscotch cake',
        category : 'Cake',
        rating : 4.3,
        price : 109,
        img : 'images/cake/25.jpg',
        quantity : 1,
    },
    ]
    export {foodItem};